// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn3UicpdlWgliN_UiefVWTYHGmCQo6foc',
    appId: '1:192456629179:web:cdb47c52371220db46429e',
    messagingSenderId: '192456629179',
    projectId: 'testing-817dc',
    authDomain: 'testing-817dc.firebaseapp.com',
    storageBucket: 'testing-817dc.appspot.com',
    measurementId: 'G-DE6ZVJWK65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNHKat_gXh7f8ZyQbbjIaCKCS_rNta1-Y',
    appId: '1:192456629179:android:df9dd7a05262c99046429e',
    messagingSenderId: '192456629179',
    projectId: 'testing-817dc',
    storageBucket: 'testing-817dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6Wu215419dnlSAO-GAkbxJ1c8c-VSmu4',
    appId: '1:192456629179:ios:c59212f3e22ddeb946429e',
    messagingSenderId: '192456629179',
    projectId: 'testing-817dc',
    storageBucket: 'testing-817dc.appspot.com',
    iosBundleId: 'com.mayar.turnierproto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6Wu215419dnlSAO-GAkbxJ1c8c-VSmu4',
    appId: '1:192456629179:ios:3ed55a26fbc9b62f46429e',
    messagingSenderId: '192456629179',
    projectId: 'testing-817dc',
    storageBucket: 'testing-817dc.appspot.com',
    iosBundleId: 'com.example.trainer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn3UicpdlWgliN_UiefVWTYHGmCQo6foc',
    appId: '1:192456629179:web:4a048894cb4b652346429e',
    messagingSenderId: '192456629179',
    projectId: 'testing-817dc',
    authDomain: 'testing-817dc.firebaseapp.com',
    storageBucket: 'testing-817dc.appspot.com',
    measurementId: 'G-YRCQJ4SX3X',
  );
}
